### ISSUE TITLE
Code verbatim content is not outputted if another code block exists in a second section

### ISSUE THREAD

**Issue by pwithnall** [projectmallard/mallard-ducktype#2]
Test case:

```
= Multi-code test

== Some title

[code]
  Some code

== Some other title

[code]
  Some other code
```

**Comment by shaunix** [comment]
Playing with this some, I think the [code] in the second second is a red herring. The first [code] is still empty if the second section has different contents. And the first [code] is correct if you put a paragraph after it. I think the actual culprit is that the [code] is effectively terminated by the section title. Probably not correctly pushing block values (using DuckParser._push_value) in that code path.
